### ISSUE TITLE
Feature request: “First Monday before date”

### ISSUE THREAD

**Issue by JordanMarr** [Jlobblet/Fugit#2]
It would be very useful to be able to ask for stuff like “the first Monday before {date}”, or “the second Tuesday of the month”.

**Comment by Jlobblet** [comment]
I would really like to add this feature. I'm current puzzling about how to word this (writing this library involves a lot of thinking about how time is described in English). I can't overload `before` and `after` without moving their `TimeSpan` parameters to an ADT and then matching on it, which I'm not especially keen on - I'd like the functions to work on a typical input (such as existing `TimeSpan` objects) without forcing users to go through a layer of transforming data to my own format. 

This is leading me towards a new function. With your sentences in mind:
```f#
theFirst Monday |> before' (January 1 2000)
theFirst Tuesday |> after' (January 1 2000)
```
I picture `theFirst` creating a record type, defined something like:
```f#
type placeholder = { n: int; dayOfWeek: DayOfWeek; }
```
with `n = 1`.  
This also allows extension to `theNth` rather than defining only `theFirst`, `theSecond`, `theThird`, etc. to some arbitrary point.
`before'`'s and `after'`'s signature would be like
```f#
val before' : DateTime -> placeholder -> DateTime
val after' : DateTime -> placeholder -> DateTime
```
However I'm not happy with the names `before'` and `after'` since they're too similar to `before` and `after`.

**Comment by JordanMarr** [comment]
Probably the most common use for this feature will be to calculate holidays:

- Birthday of Martin Luther King Jr. - 3rd Monday in January
- George Washington's Birthday - 3rd Monday in February
- Labor Day - 1st Monday in September
- Columbus Day - 2nd Monday in October
- Thanksgiving Day - 4th Thursday in November

Which isn't exactly my use case, but probably would be a better driver for the feature.

let mlk = theThird Monday |> in' (January 2021)
let thanksgiving = theFourth Thursday |> in' (November 2021)

**Comment by Jlobblet** [comment]
I think I'll be using `of'` for the name of the function in this context:
```fs
let mlk = theThird Monday |> of' (January 2021)
```
Which leaves me with two more issues: `January` and how to get the _last_ occurrence of a day of the week.

Currently, both `January` and `January'` are used in `Fugit.Months` for constructing a particular date: `January 28 2000` and `28 |> January' 2000` respectively. This doesn't support using them to refer to the month itself as a period of time, rather than a particular date.

The last occurrence is also tricky. `theLast` is used to construct a pair of DateTimes as a period (`every (5 |> minutes) in' (theLast hour)`) but it's also the natural way of expressing some times, e.g. "the last Monday before January 1 2000".

**Comment by JordanMarr** [comment]
Since some of these functions can be used in different contexts, maybe it would help to put them in different modules. 
Ex: `every (5 |> minutes) in' (Hours.last hour)`?

`Months.last`
`Hours.last`
`Days.last`

etc...
Adding the module name isn't quite as natural sounding to read, but people can always create local bindings as needed for their context. 
Ex:
```fsharp
let theLast = Hours.last
every (5 |> minutes) in' (theLast hour)
```

This might help prevent having a bunch of functions with apostrophes at the end, which I personally confusing.

Just food for thought. Obviously there are many paths here, which does indeed make it difficult to craft the perfect API.

**Comment by Jlobblet** [comment]
The existing `theLast` (which I just realised I hadn't pushed yet) works as a constructor for a PeriodBoundaries:
https://github.com/Jlobblet/Fugit/blob/6be2fe58d6e246e36a105b16183108392b8842cc/src/Fugit/Fugit.fs#L102-L106
rather than as one for a particular denomination of time. 
`in'` is then just an alias for `between`, since
```f#
every (5 |> minutes) |> between (theLast hour)
```
doesn't really read particularly well, even if it executes the same code.

**Comment by Jlobblet** [comment]
Having deliberated on it for a bit, I think I'll make it part of another module with `[<RequireQualifiedAccess>]` to avoid accidental collisions, and allow people to create their own bindings.

**Comment by JordanMarr** [comment]
This seems like a good decision as it will allow you to focus on providing the basic building blocks for users to compose with, and it lets you sidestep the potential trap of trying to encode every single permutation of the building blocks yourself.

**Comment by Jlobblet** [comment]
Implemented in 1d7effb44379272a0c8ddb9fc4a83623a09bc2f1, and tests in 933fc95796d4ae5c5df8179dfe4134c73a328d5f.
All tests pass after running locally.
Still todo:
- [x] Write in-code documentation for the new functions
- [x] Write CI to run tests automatically
- [x] Release version 0.3.0, containing these changes

**Comment by Jlobblet** [comment]
I have now released version 0.3.0 with these changes included. I'm happy to hear any feedback on the documentation of the new functions, for example:
https://github.com/Jlobblet/Fugit/blob/c8cc4009a8c2ca3d9dc6f6976949b7cd58daaf00/src/Fugit/DayOfWeek.fs#L52-L56
If everything seems ok after a short while I'll close this issue.

**Comment by JordanMarr** [comment]
Cool! I will check it out.

**Comment by JordanMarr** [comment]
It worked first try!

```fsharp
    open Fugit

    [<Test>]
    let ``Fugit Holidays``() = 
        let mlk = DayOfWeek.theThird DayOfWeek.Monday |> DayOfWeek.afterOrEqual (DateTime(2021, 1, 1))
        mlk |> should equal (DateTime(2021, 1, 18))

        let laborDay = DayOfWeek.theFirst DayOfWeek.Monday |> DayOfWeek.afterOrEqual (DateTime(2021, 9, 1))
        laborDay |> should equal (DateTime(2021, 9, 6))

        let thanksgiving = DayOfWeek.theFourth DayOfWeek.Thursday |> DayOfWeek.afterOrEqual (DateTime(2021, 11, 1))
        thanksgiving |> should equal (DateTime(2021, 11, 25))

```

**Comment by Jlobblet** [comment]
I used some of these in the tests in this repo
https://github.com/Jlobblet/Fugit/blob/4e406ea0d1a6449d077f71721288e83029ab4873/tests/Fugit.Tests/DayOfWeek.fs#L94-L130

**Comment by JordanMarr** [comment]
I missed the cool date format ‘September 1 2021’ in mine. That’s a nice touch.

**Comment by Jlobblet** [comment]
Haven't heard anything new on this issue. Closing.
